name: "Build and push images dockerhub"

on:
  push:
    branches: [ master ]
  release:
    types:
      - published
jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest 
   
    steps:
      - name: Check out
        uses: actions/checkout@v2      
      
      - name: login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: darkcloud784/exodusbot
          tags: |
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./dockerfile
          
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
              darkcloud784/exodusbot:latest
              darkcloud784/exodusbot